Fixes #12 Zooming
graph-genome/component_segmentation pull request #35
Opened 2020-04-09 21:05 UTC by mandosoft

2020-04-10 07:28 UTC, subwaystation commented
Hi @mandosoft 
I just merged the parallel JSON processing into master, so please resolve the merge conflicts. Thanks!

2020-04-10 17:04 UTC, mandosoft commented
Resolved conflicts. Let me know if anything else needs fixing. Thanks!

2020-04-10 18:13 UTC, josiahseaman commented
@mandosoft I'm still not seeing any unique commit messages.  Is this ready for review?  Please change your commit message each time you commit something.

2020-04-21 18:41 UTC, mandosoft commented
@josiahseaman check the latest and let me know if there are any other changes necessary. Thanks!

2020-04-21 23:03 UTC, josiahseaman requested changes
I wasn't able to finish testing because of the errors I ran into early with filenames.  Please provide the command and file layout you used to test.

2020-04-21 23:03 UTC, josiahseaman commented on segmentation.py
> +        path_name = json_file.split(".json")[0].split("/")[1]
It's much better to use pathlib for this kind of operation.  This will for example break on file.json.gz as well as windows paths.

2020-04-21 23:03 UTC, josiahseaman commented on segmentation.py
> +        files = glob.glob(str(osPath(args.json_file).parent) + "/*.w*.json")  # glob dir into file list
This is incorrect.  You're discarding the file name or prefix by taking .parent, this grabs the parent directory of the "file".  On my computer "data/run1.B1phi1.i1.seqwish*" will start by  "reading data\lung_cancer.w1000.json" since they're in the same directory.  Rather than stripping and adding *.json, you should just leave the user provided prefix as is and have the user add the * themselves

2020-04-21 23:03 UTC, josiahseaman commented on segmentation.py
> +        files = glob.glob(str(osPath(args.json_file).parent) + "/*.w*.json")  # glob dir into file list
```
Traceback (most recent call last):
  File "D:/josiah/Projects/component_segmentation/segmentation.py", line 381, in <module>
Created 4576 LinkColumns
    main()
  File "D:/josiah/Projects/component_segmentation/segmentation.py", line 372, in main
    path_name = json_file.split(".json")[0].split("/")[1]
IndexError: list index out of range
```
Using the arguments: `--json-file=data/run1.B1phi1.i1.seqwish/run1.B1phi1.i1.seqwish* --cells-per-file=5000`
I moved the target files into a subdirectory, but it still errors out.  
adding the expected .json at the end yields:
```
Traceback (most recent call last):
  File "D:/josiah/Projects/component_segmentation/segmentation.py", line 381, in <module>
    main()
  File "D:/josiah/Projects/component_segmentation/segmentation.py", line 359, in main
    args = get_arguments()
  File "D:/josiah/Projects/component_segmentation/segmentation.py", line 349, in get_arguments
    os.makedirs(args.output_folder, exist_ok=True)
  File "D:\Anaconda3\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'data/run1.B1phi1.i1.seqwish/run1.B1phi1.i1.seqwish*.json'
```

2020-04-21 23:49 UTC, closed without merging